### ISSUE TITLE
Passing bearer token to LHS

### ISSUE THREAD

**Issue by acoiro** [local-ch/lhs#116]
I didn't find a good way to pass the access token to LHS yet. We were using RequestStore' gem first, then switched to `Thread` but it didn't help, we are still getting the issue `"Invalid access token: ''"`. Somehow it gets lost, even if the cookie is set and it contains a valid `access_token`.

The only fix was to replace LHS with LHC, but this is something that makes me sad.

Any idea?

**Comment by pape-io** [comment]
I think then there is nothing else left then to be explicit:
```
#controllers/some_controller.rb

def index
  Records.auth(bearer: '12345').where(name: 'Steve')
end
```

What do you think @acoiro

**Comment by pape-io** [comment]
As this follows MVC strictly, there shouldn't be a problem with it.

To not end up with a lot of `.auth(bearer: access_token)` lines you could dry it up to something like:

```
# application_controller
def auth(record)
  record.auth(bearer: access_token)
end
```

```
# controllers/some_controller.rb

def index
  auth(Record).where(name: 'Steve')
end
```

**Comment by pape-io** [comment]
Just take care that everything stays in Rails controller context, as we have to mess with passing the auth_token around again.

**Comment by pape-io** [comment]
As LHS is not aware of request based options yet and especially not about auth and I don't want to create any coupling to lhc-core-interceptors, why I suggest to do it a little more generic as before:

```
# application_controller
def authed(record)
  record.options(auth: { bearer: access_token })
end
```

```
# controllers/some_controller.rb

def index
  authed(Record).where(name: 'Steve')
end
```

This way you could pass any options done during the chain.

**Comment by acoiro** [comment]
Ok thanks, I am going to try it. I will first add more info to the exception so that I can understand what is wrong with thread. https://github.com/local-ch/ws-customer-center/pull/261

**Comment by pape-io** [comment]
@acoiro the `options` is not yet implemented in LHS. I would have to add it.

**Comment by pape-io** [comment]
Fixed in https://github.com/local-ch/lhs/releases/tag/v5.1.0
