### ISSUE TITLE
Get ID of LHS::Record

### ISSUE THREAD

**Issue by Averethel** [local-ch/lhs#124]
How about adding the following:

```ruby
  def id
    return if href.nil?

    href.split('/').last
  end
```

to LHS::Record?

At the moment we don't have a way to get JUST the ID. Or is it hidden somewhere?

**Comment by pape-io** [comment]
dont use IDs

**Comment by pape-io** [comment]
use hrefs

**Comment by pape-io** [comment]
and even more important, dont make generel assumptions on where the id is located in the href

**Comment by Averethel** [comment]
We need to send IDs for the audit trail. Using href is not an option there.

**Comment by Averethel** [comment]
About the assumption - we can figure that from the URL template given to the record no? This was just an example

**Comment by pape-io** [comment]
With templates, that could work out. We were able to send href when dealing with records. Can you elaborate why working with hrefs is *not* possible?

**Comment by pape-io** [comment]
Something you also have to consider: potential shadowing an underlying datum with the key 'id'

**Comment by gonzalocasas** [comment]
This issue has a lot of flame-war potential.
Probably getting IDs of entities is not something that can be generalized to this layer.

Using `href` is only ok if you stay in the real of REST calls, but as soon as you need to store data somewhere that refers to an entity, is just wrong to use `href` instead of the real object id. Using `href`s on other layers means you're leaking an abstraction and making it pervasive to the domain model for no reason; you're making object identity a technology-dependent attribute.

**Comment by pape-io** [comment]
What's the difference between an ID and an HREF, both are just strings.

**Comment by pape-io** [comment]
The only difference is that at some point you will try to rebuild the ID to get it's actual location at some point and that's simply hackish.

**Comment by pape-io** [comment]
How is it technology-dependent?

**Comment by Averethel** [comment]
About shadowing - fair point but we can have reserved keywords/do it with underscore/or only do it when the ID is not provided.

About working with hrefs - you don't want to do it in the audit trail, There you just want to have a reference to the record to insert in your audit DB (as @gonzalocasas wrote).

And we SHOULD be able to get the record id somehow no?

**Comment by pape-io** [comment]
It's so simple, if you really need the ID to store. Negotiate it with the backend to provide it in it's on field, but don't rip it out of the href!

**Comment by gonzalocasas** [comment]
> How is it technology-dependent?
`href` is dependent on HTTP technology.

**Comment by pape-io** [comment]
it's just a string, how is this dependent to technology?

**Comment by pape-io** [comment]
And taking the ID out of the href is coupling by example, and violates the basic principle, which weights more then all the buzzwords you came up with so far.

**Comment by gonzalocasas** [comment]
If an object would not have a real identifier, then I'd agree they are the same; but objects do not exists solely on RESTland, our objects have identifiers and we want to use them, we need to refer to them in contexts other than REST calls.

If I asked you to replace those hrefs with a "disk sector location", I could also claim is "only strings" and not technology-dependent. And it would be true at some point, but you don't want to use a string that refers to a particular technology (that might go away at some point, and actually, disk sectors are less  likely to go away than REST, but that still doesn't make them any more viable as a synthetic identifier).

**Comment by gonzalocasas** [comment]
But again, I am NOT saying we should be able to get the id out of the href. Getting IDs of objects belongs to the business models, not to LHS

**Comment by pape-io** [comment]
Then use the ID, but href is not the ID as you just described so nicely your self! Think about it.

**Comment by pape-io** [comment]
I think we agree all that ID should be provided from the service. Am I right?

**Comment by gonzalocasas** [comment]
yep 😄

**Comment by Averethel** [comment]
ping @ractive

**Comment by ractive** [comment]
All are valid points... I'll send the feedback id with the response.
