### ISSUE TITLE
Overriding options through includes and references doesn't seem to work

### ISSUE THREAD

**Issue by nerdinand** [local-ch/lhs#207]
When I request

```ruby
Customer.options(auth: {bearer: 'token-1'}).includes(:places).references(places: {auth: {bearer: 'token-2'}}).find_by(id: 42)
```

I expect the token in the places request to be `token-2`, but it is `token-1`.

**Comment by spape** [comment]
It's a special situation. references has the correct options for places, but these special options (for e.g. auth) are not forwarded in the special scenarion where the expanded data is just a collection of links, which required additional expanding. During the additional expansion, the options are not applied, therfor the request is not authenticated.

**Comment by spape** [comment]
Fixed in https://github.com/local-ch/lhs/pull/208, please test RC
