### ISSUE TITLE
Nested collection thinks it's an item

### ISSUE THREAD

**Issue by Averethel** [local-ch/lhs#215]
I have the following case:

```ruby
rs = Restaurant.includes(place: :feedbacks).where(...)
fs = rs.first.place.feedbacks
# =>
# Data of Restaurant 
# > place > feedbacks
# :href => "xxx"
# :items => [{:href=> "xxx" } ... ]
fs.item?
# =>
true
```

check free-table-search app / feedback-migration branch

**Comment by spape** [comment]
Why it happens:
While navigating/accessing data, LHS applies configuration from last recognized Record.

When drilling down from Restaurant, which is a search results and identifies collections with `docs` as configured in `Restaurant` it applies this configuration when accessing `feedbacks` to.

As feedbacks has `items` do identify collections, LHS does not recognize it as collection.

In a patch I will try to identify Records when accessing collections, what was intendend by you when adding `:datastore/feedbacks` endpoint to the `Feedback` record.

Right now, only items are identified/recognize when accessing.

**Comment by spape** [comment]
Fixed in https://github.com/local-ch/lhs/releases/tag/v11.0.2
