### ISSUE TITLE
Make #map available for Hash

### ISSUE THREAD

**Issue by christianarevalo** [local-ch/lhs#254]
Consider the following use case, fetching one category
```
category = Category.find("http://test.com/categories/1")
```
You receive similar data
```
{
    "id": "1",
    ...
    "languages": {
        "en": {
            "href": "http://test.com/categories/1/en",
            "name": "Category 1 EN",
        },
        "de": {
            "href": "http://test.com/categories/1/de",
            "name": "Category 1 DE",
        },
        # More languages
        }
    }
}
```

Then we would like to apply a map to `category.languages` but it's not working as expected. Therefore, I have to get `as_json` to be able to iterate over the items.

**Comment by spape** [comment]
Fixed in https://github.com/local-ch/lhs/pull/255
