### ISSUE TITLE
Error handling on subresources

### ISSUE THREAD

**Issue by skaestle** [local-ch/lhs#49]
https://github.com/local-ch/location-app/pull/1080

We had a case with the Favorites service where one 404 on the places resource would lead to the whole request being error'ed out with `LHC::NotFound`

In this case it would have been great if I could have told LHS: "hey I don't mind if i get an error on a subresource, just return to me what you have"

**Comment by pape-io** [comment]
Will take care ;)

**Comment by pape-io** [comment]
duplicate of https://github.com/local-ch/lhs/issues/46
