### ISSUE TITLE
revisit map interface

### ISSUE THREAD

**Issue by skaestle** [local-ch/lhs#5]
```ruby

module Services
  class TermsAndConditions < LHS::Service
    endpoint "#{LCL[:datastore_service]}/v2/agbs/active"

    map :pdf_url, ->(agb) { agb["binary_url_pdf_#{I18n.locale}"] }

    def pdf_url
      send("binary_url_pdf_#{I18n.locale}")
    end
  end
end

```

It would be nice if we could revisit the mapping interface, I think it would profit from getting closer to what normal ruby looks like.

**Comment by pape-io** [comment]
First step: https://github.com/local-ch/lhs/pull/35

**Comment by pape-io** [comment]
Will be fixed with: https://github.com/local-ch/lhs/pull/67

**Comment by pape-io** [comment]
Fixed with https://github.com/local-ch/lhs/releases/tag/v3.0.0
