### ISSUE TITLE
mocking get requests with plain arrays are not supported anymore

### ISSUE THREAD

**Issue by ryabrody** [local-ch/lhs#79]
in version `1.2.2` it was possible to mock get requests in specs like this
spec/features/gtm/callcenters_cd_spec.rb (location-app)
```ruby
let(:callcenter) do
  FactoryGirl.build(:spamnumber_hash, :as_callcenter, formatted_number: '044 551 00 03')
end
let(:callcenters) { [callcenter] } 

before :each do
  stub_request(:get, %r{/spamnumbers}).to_return(body: callcenters.to_json)
  visit_tel('/en/advertising-calls?what=Hans&where=Lucerne')
end
```

in version `2.1.0` it is not possible anymore and we have to do it like this:
```ruby
let(:callcenters) { { items: [callcenter] } }
```

**Comment by pape-io** [comment]
It's working in v3 https://github.com/local-ch/lhs/commit/8e181a1fa322f23efe66ca656000f357fb00dbb6
As we have to motivate people to update, you have to live with the inconvenience.

**Comment by ryabrody** [comment]
@pape-io 
You do not Backport it?
