### ISSUE TITLE
Record / method forwarding issues

### ISSUE THREAD

**Issue by acoiro** [local-ch/lhs#92]
I am unable to call any array method on my `User` object (e.g. for `claims` or `accepted_agbs`)

I believe the problem is that I get back an `OpenStruct` object instead of `LHS::Data`

v3.3.5

**Comment by pape-io** [comment]
I kindly ask you to write a test that reproduces the problem next time.

Franca did a nice example lately: https://github.com/local-ch/lhs/pull/89

That way it is quite efficient solving bugs. 

It would allow me to dive into the problem way faster and it would release you to write perfect Issue descriptions, which are never perfect.

**Comment by pape-io** [comment]
Problem solved.
In this case initialisation of `LHS::Record` was not done with raw json but with some pre-marshalled ruby objects (open structs).
